version: "3"

services:
  backend:
    container_name: backend
    build:
      context: ./requirement/backend
      dockerfile: Dockerfile
    depends_on:
      - db
    networks:
      - transcendence
    ports:
      - "3001:3001"
    restart: always
    volumes:
      - ./backend:/app

  db:
    image: postgres
    container_name: database
    environment:
      PGPORT: 5432
      POSTGRES_USER: mpatel
      POSTGRES_PASSWORD: transcendence
      DB_DATABASE: ft_database
    volumes:
      - ./requirement/database/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - transcendence
    command: postgres
    restart: always

networks:
  transcendence:
