version: '3'
services:
  postgres:
    image: postgres:13.4-buster
    container_name: postgres
    environment:
      PGPORT: 5432
      POSTGRES_USER: mpatel
      POSTGRES_PASSWORD: transcendenceProd
      DB_DATABASE: ft_database
    ports:
      - "5432:5432"
    networks:
      - transcendenceProd
    volumes:
      - ./requirement/database/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./requirement/nginx/:/etc/nginx/
      - ./frontend/build:/var/www/html
    ports:
      - 80:80
    command: /bin/sh -c "nginx -g 'daemon off;'"
    depends_on:
      - reactjs
    networks:
      - transcendenceProd
  reactjs:
    image: node:19
    container_name: reactjs
    working_dir: /app/frontend
    env_file:
      - .env
    command: >
      bash -c "npm install
      && npm run build"
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    networks:
      - transcendenceProd
    depends_on:
      - nestjs
  nestjs:
    image: node:19
    container_name: nestjs
    working_dir: /app/backend
    command: >
      bash -c "npm install
      && npx prisma db push
      && npx prisma db seed
      && npm run build
      && npm run start:prod
      && npm i -g @nestjs/cli"
    networks:
      - transcendenceProd
    ports:
      - "3001:3001"
      - "5555:5555"
      - "8001:8001"
      - "8002:8002"
    env_file:
      - .env
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    depends_on:
      - postgres
volumes:
  postgres_data:
networks:
  transcendenceProd:
    driver: bridge
    name: transcendenceProd
