version: '3'
services:
  postgres:
    image: postgres:13.4-buster
    container_name: postgres
    environment:
      PGPORT: ${PGPORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    ports:
      - "5432:5432"
    networks:
      - transcendenceDev
    volumes:
      - ./requirement/database/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
  reactjs:
    image: node:19
    container_name: reactjs
    working_dir: /app/frontend
    command: >
      bash -c "npm install
      && npm start"
    ports:
      - "3000:3000"
    env_file:
      - .env.dev
    volumes:
      - ./srcs/frontend:/app/frontend
      - /app/frontend/node_modules
    networks:
      - transcendenceDev
    depends_on:
      - nestjs
  nestjs:
    image: node:19
    container_name: nestjs
    working_dir: /app/backend
    command: >
      bash -c "npm install
      && npm i -g @nestjs/cli
      && npx prisma db push
      && npx prisma db seed
      && npm run start:dev"
    networks:
      - transcendenceDev
    ports:
      - "3001:3001"
      - "5555:5555"
      - "8001:8001"
      - "8002:8002"
    env_file:
      - .env.dev
    volumes:
      - ./srcs/backend:/app/backend
      - /app/backend/node_modules
    depends_on:
      - postgres
volumes:
  postgres_data:
networks:
  transcendenceDev:
    driver: bridge
    name: transcendenceDev
