version: '3'
services:
  postgres:
    image: postgres:13.4-buster
    environment:
      PGPORT: 5432
      POSTGRES_USER: mpatel
      POSTGRES_PASSWORD: transcendence
      DB_DATABASE: ft_database
    ports:
      - "5432:5432"
    volumes:
      - ./requirement/database/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
  nestjs:
    image: node:19
    working_dir: /app/backend
    command: bash -c "npm install && npm run start:dev"
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:example@postgres:5432/mydb
    volumes:
      - ./backend:/app/backend
    depends_on:
      - postgres
volumes:
  postgres_data:
