version: "3"

services:
  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: ./requirement/backend/Dockerfile
    depends_on:
      - database
    networks:
      - transcendence
    ports:
      - "3001:3001"
    restart: always
    env_file:
      - .env

  db:
    image: postgres:12
    container_name: database
    environment:
      PGPORT: ${DB_PGPORT}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    env_file:
      - ./requirement/postgres.env
    volumes:
      - ./requirement/database/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - transcendence
    command: postgres
    restart: always

networks:
  transcendence:
