version: '3'
services:
  postgres:
    image: postgres:13.4-buster
    container_name: postgres
    environment:
      PGPORT: 5432
      POSTGRES_USER: mpatel
      POSTGRES_PASSWORD: transcendence
      DB_DATABASE: ft_database
    ports:
      - "5432:5432"
    volumes:
      - ./requirement/database/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
  nestjs:
    image: node:19
    container_name: nestjs
    working_dir: /app/backend
    command: >
      bash -c "npm install
      && npm run start:dev
      && npm i -g @nestjs/cli"
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://mpatel:transcendence@172.18.0.2:5432/ft_database?schema=public
    volumes:
      - ./backend:/app/backend
    depends_on:
      - postgres
volumes:
  postgres_data:
